version: '2'
services:
  jenkins:
    container_name: jenkins
    image: otaviera/jenkins-docker
    environment:
#### Option for a specific cacerts, disable SNI extension and endpoint identification 
    - JAVA_OPTS=-Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.trustStore=/var/jenkins_home/.cacerts/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true -Djsse.enableSNIExtension=false
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - /storage/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
#### Mapping User Jenkins (1000) to Group Docker (994)
    user: "1000:994"
